[package]
name = "nova-devtools"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
nova-core = { path = "../nova-core" }
serde.workspace = true
serde_json.workspace = true
toml = "0.8"

[dev-dependencies]
tempfile.workspace = true
