[package]
name = "nova-archive"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile = "3"
