[package]
name = "nova-flow"
version.workspace = true
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-hir = { path = "../nova-hir" }
nova-types = { path = "../nova-types" }

[dev-dependencies]

