[package]
name = "nova-storage"
version.workspace = true
edition = "2021"

[dependencies]
blake3 = "1.5"
byteorder = "1"
memmap2 = "0.9"
nova-core = { path = "../nova-core" }
rkyv = { version = "0.7", features = ["validation"] }
thiserror = "1"
tracing = { workspace = true }
zstd = "0.13"

[dev-dependencies]
tempfile = "3.10"
