[package]
name = "nova-stream-debug"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-jdwp = { path = "../nova-jdwp" }
nova-types = { path = "../nova-types" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
