[package]
name = "nova-types"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
nova-ids = { path = "../nova-ids" }

[dev-dependencies]
pretty_assertions = "1.4"
nova-classpath = { path = "../nova-classpath" }
nova-test-utils = { path = "../nova-test-utils", default-features = false, features = ["javac"] }
nova-types-bridge = { path = "../nova-types-bridge" }
