[package]
name = "nova-types"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
nova-ids = { path = "../nova-ids" }
nova-classfile = { path = "../nova-classfile" }

[dev-dependencies]
pretty_assertions = "1.4"
nova-test-utils = { path = "../nova-test-utils" }
nova-classpath = { path = "../nova-classpath" }
