[package]
name = "nova-jdk"
version.workspace = true
edition = "2021"

[dependencies]
nova-cache = { path = "../nova-cache" }
nova-core = { path = "../nova-core" }
nova-classfile = { path = "../nova-classfile" }
nova-modules = { path = "../nova-modules" }
nova-process = { path = "../nova-process" }
nova-storage = { path = "../nova-storage" }
nova-types = { path = "../nova-types" }
once_cell = "1"
rkyv = { version = "0.7", features = ["validation"] }
thiserror = "1"
tracing = { workspace = true }
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
nova-config = { path = "../nova-config" }
nova-test-utils = { path = "../nova-test-utils", default-features = false }
tempfile = "3"
