[package]
name = "nova-jdk"
version.workspace = true
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-classfile = { path = "../nova-classfile" }
nova-modules = { path = "../nova-modules" }
nova-process = { path = "../nova-process" }
nova-types = { path = "../nova-types" }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1"
thiserror = "1"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
nova-config = { path = "../nova-config" }
tempfile = "3"
