[package]
name = "nova-jdk"
version.workspace = true
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-classfile = { path = "../nova-classfile" }
nova-modules = { path = "../nova-modules" }
nova-types = { path = "../nova-types" }
once_cell = "1"
thiserror = "1"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile = "3"
