[package]
name = "nova-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-hir = { path = "../nova-hir" }
nova-types = { path = "../nova-types" }
nova-vfs = { path = "../nova-vfs" }
