[package]
name = "nova-perf"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.79"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
toml = "0.8.10"
walkdir = "2.5.0"

[dev-dependencies]
tempfile.workspace = true
