[package]
name = "nova-refactor"
version.workspace = true
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-format = { path = "../nova-format" }
nova-index = { path = "../nova-index" }
nova-build-model = { path = "../nova-build-model" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
lsp-types = "0.97"
regex = "1"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
similar = "2.4"
thiserror = "1.0"
nova-db = { path = "../nova-db" }
nova-hir = { path = "../nova-hir" }
nova-flow = { path = "../nova-flow" }
nova-jdk = { path = "../nova-jdk" }
nova-resolve = { path = "../nova-resolve" }

[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4"
nova-test-utils = { path = "../nova-test-utils" }

[[bench]]
name = "refactor"
harness = false

[[test]]
name = "javac_refactors"
path = "tests/harness/javac_refactors.rs"
