[package]
name = "nova-refactor"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-index = { path = "../nova-index" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nova-project = { path = "../nova-project" }
tree-sitter = "0.20"
tree-sitter-java = "0.20"

[dev-dependencies]
pretty_assertions = "1.4"
nova-test-utils = { path = "../nova-test-utils" }
