[package]
name = "nova-vfs"
version.workspace = true
edition = "2021"

[features]
default = []
lsp = ["nova-core/lsp", "dep:lsp-types"]

[dependencies]
nova-core = { path = "../nova-core" }
nova-archive = { path = "../nova-archive" }
lsp-types = { version = "0.97.0", optional = true }

[dev-dependencies]
tempfile = "3"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
