[package]
name = "nova-vfs"
version.workspace = true
edition = "2021"

[features]
default = []
lsp = ["nova-core/lsp", "dep:lsp-types"]
watch-notify = ["dep:notify"]

[dependencies]
nova-core = { path = "../nova-core" }
nova-archive = { path = "../nova-archive" }
tracing = { workspace = true }
lru = "0.12"
hashbrown = "0.16"
lsp-types = { version = "0.97.0", optional = true }
crossbeam-channel = "0.5"
notify = { version = "6.1", optional = true }

[dev-dependencies]
tempfile = "3"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
notify = "6.1"
