[package]
name = "nova-config"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.8"
url = { version = "2", features = ["serde"] }
