[package]
name = "nova-db"
version.workspace = true
edition = "2021"

[features]
# Enable additional `tracing` spans/logs for query execution.
tracing = []

[dependencies]
nova-cache = { path = "../nova-cache" }
nova-core = { path = "../nova-core" }
nova-hir = { path = "../nova-hir" }
nova-project = { path = "../nova-project" }
nova-syntax = { path = "../nova-syntax" }
parking_lot = "0.12"
ra_salsa = { package = "ra_ap_salsa", version = "0.0.269" }
tracing = "0.1"
nova-memory = { path = "../nova-memory" }
thiserror = "2"
serde = "1"

[dev-dependencies]
bincode = "1"
tempfile = "3"
serde = { version = "1", features = ["derive"] }

[lib]
path = "src/lib.rs"
