[package]
name = "nova-remote-rpc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
zstd = "0.13"

[dev-dependencies]
tracing-subscriber.workspace = true
