[package]
name = "nova-remote-rpc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
nova-remote-proto = { path = "../nova-remote-proto" }
zstd = "0.13"

[dev-dependencies]
tracing-subscriber.workspace = true
proptest = "1"
