[package]
name = "nova-ide"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-project = { path = "../nova-project" }
nova-fuzzy = { path = "../nova-fuzzy" }
nova-db = { path = "../nova-db" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
nova-refactor = { path = "../nova-refactor" }
lsp-types = "0.97"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"

[lib]
path = "src/lib.rs"
