[package]
name = "nova-ide"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-ai = { path = "../nova-ai", optional = true }
nova-config = { path = "../nova-config" }
nova-core = { path = "../nova-core" }
nova-decompile = { path = "../nova-decompile" }
nova-project = { path = "../nova-project" }
nova-fuzzy = { path = "../nova-fuzzy" }
nova-db = { path = "../nova-db" }
nova-index = { path = "../nova-index" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
nova-refactor = { path = "../nova-refactor" }
lsp-types = "0.97"
nova-ext = { path = "../nova-ext" }
nova-scheduler = { path = "../nova-scheduler" }
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
nova-framework-spring = { path = "../nova-framework-spring" }
nova-framework-micronaut = { path = "../nova-framework-micronaut" }

[features]
ai = ["dep:nova-ai"]

[lib]
path = "src/lib.rs"

[dev-dependencies]
nova-framework = { path = "../nova-framework" }
