[package]
name = "nova-ide"
version.workspace = true
edition = "2021"

[dependencies]
nova-ai = { path = "../nova-ai", optional = true }
nova-config = { path = "../nova-config" }
nova-config-metadata = { path = "../nova-config-metadata" }
nova-core = { path = "../nova-core" }
nova-decompile = { path = "../nova-decompile" }
futures = "0.3"
tokio = { workspace = true, optional = true, features = ["macros", "time"] }
tokio-util = { version = "0.7", optional = true }
nova-classpath = { path = "../nova-classpath" }
nova-project = { path = "../nova-project" }
nova-fuzzy = { path = "../nova-fuzzy" }
nova-db = { path = "../nova-db" }
nova-framework = { path = "../nova-framework" }
nova-framework-lombok = { path = "../nova-framework-lombok" }
nova-index = { path = "../nova-index" }
nova-hir = { path = "../nova-hir" }
nova-resolve = { path = "../nova-resolve" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
nova-refactor = { path = "../nova-refactor" }
lsp-types = "0.97"
nova-ext = { path = "../nova-ext" }
nova-scheduler = { path = "../nova-scheduler" }
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
nova-framework-spring = { path = "../nova-framework-spring" }
nova-framework-micronaut = { path = "../nova-framework-micronaut" }
nova-framework-jpa = { path = "../nova-framework-jpa" }
nova-framework-dagger = { path = "../nova-framework-dagger" }
tree-sitter = "0.20"
tree-sitter-java = "0.20"

[features]
ai = ["dep:nova-ai", "dep:tokio", "dep:tokio-util"]

[lib]
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
