[package]
name = "nova-types-bridge"
version.workspace = true
edition = "2021"

[dependencies]
nova-classfile = { path = "../nova-classfile" }
nova-types = { path = "../nova-types" }
nova-types-signature = { path = "../nova-types-signature" }
thiserror = "1"
