[package]
name = "nova-hir"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-types = { path = "../nova-types" }
nova-syntax = { path = "../nova-syntax" }
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
