[package]
name = "nova-hir"
version.workspace = true
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-types = { path = "../nova-types" }
nova-syntax = { path = "../nova-syntax" }
nova-modules = { path = "../nova-modules" }
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
nova-vfs = { path = "../nova-vfs" }
thiserror = "1.0"
