[package]
name = "nova-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-index = { path = "../nova-index" }
lsp-types = "0.97"
nova-ide = { path = "../nova-ide" }
tempfile.workspace = true
