[package]
name = "nova-test-utils"
version.workspace = true
edition = "2021"

[dependencies]
nova-index = { path = "../nova-index", optional = true }
lsp-types = { version = "0.97", optional = true }
nova-ide = { path = "../nova-ide", optional = true }
tempfile = { workspace = true, optional = true }
tracing = { workspace = true }

[features]
default = ["fixtures", "javac"]
fixtures = ["fixture-fs", "fixture-ranges", "fixture-db"]
fixture-fs = []
fixture-ranges = ["dep:nova-index"]
fixture-db = ["dep:nova-ide", "lsp-text"]
lsp-text = ["dep:lsp-types"]
javac = ["dep:tempfile"]
