[package]
name = "nova-remote-proto"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_cbor = "0.11"
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

[features]
tokio = ["dep:tokio"]

[dev-dependencies]
proptest = "1"
