[package]
name = "nova-remote-proto"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_cbor = "0.11"

[dev-dependencies]
proptest = "1"
