[package]
name = "nova-resolve"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1"
nova-core = { path = "../nova-core" }
nova-classpath = { path = "../nova-classpath" }
nova-framework = { path = "../nova-framework" }
nova-hir = { path = "../nova-hir" }
nova-jdk = { path = "../nova-jdk" }
nova-project = { path = "../nova-project" }
nova-types = { path = "../nova-types" }
nova-modules = { path = "../nova-modules" }
thiserror = "1.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3"
