[package]
name = "nova-resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-framework = { path = "../nova-framework" }
nova-hir = { path = "../nova-hir" }
nova-jdk = { path = "../nova-jdk" }
nova-types = { path = "../nova-types" }

[dev-dependencies]
nova-classpath = { path = "../nova-classpath" }
