[package]
name = "nova-resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-core = { path = "../nova-core" }
nova-hir = { path = "../nova-hir" }
nova-jdk = { path = "../nova-jdk" }

[dev-dependencies]

