[package]
name = "nova-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
lsp = ["dep:lsp-types"]

[dependencies]
dunce = "1.0.5"
lasso = "0.7.3"
smol_str = "0.2.2"
text-size = "1.1.1"

lsp-types = { version = "0.97.0", optional = true }
