[package]
name = "nova-workspace"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1"
async-channel = "2"
nova-cache = { path = "../nova-cache" }
crossbeam-channel = "0.5"
notify = "6.1"
nova-fuzzy = { path = "../nova-fuzzy" }
nova-framework-spring = { path = "../nova-framework-spring" }
nova-framework-jpa = { path = "../nova-framework-jpa" }
nova-config = { path = "../nova-config" }
nova-core = { path = "../nova-core" }
nova-db = { path = "../nova-db" }
nova-ide = { path = "../nova-ide" }
nova-index = { path = "../nova-index" }
nova-memory = { path = "../nova-memory" }
nova-project = { path = "../nova-project" }
nova-scheduler = { path = "../nova-scheduler" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
nova-vfs = { path = "../nova-vfs" }
nova-jdk = { path = "../nova-jdk" }
nova-classpath = { path = "../nova-classpath" }
rowan = "0.15.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt", "time"] }
