[package]
name = "nova-workspace"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1"
async-channel = "2"
nova-cache = { path = "../nova-cache" }
crossbeam-channel = "0.5"
nova-fuzzy = { path = "../nova-fuzzy" }
nova-framework-spring = { path = "../nova-framework-spring" }
nova-framework-jpa = { path = "../nova-framework-jpa" }
nova-config = { path = "../nova-config" }
nova-core = { path = "../nova-core" }
nova-db = { path = "../nova-db" }
nova-hir = { path = "../nova-hir" }
nova-ide = { path = "../nova-ide" }
nova-index = { path = "../nova-index" }
nova-memory = { path = "../nova-memory" }
nova-project = { path = "../nova-project" }
nova-build = { path = "../nova-build" }
nova-scheduler = { path = "../nova-scheduler" }
nova-syntax = { path = "../nova-syntax" }
nova-types = { path = "../nova-types" }
nova-vfs = { path = "../nova-vfs", features = ["watch-notify"] }
nova-jdk = { path = "../nova-jdk" }
nova-classpath = { path = "../nova-classpath" }
nova-build-model = { path = "../nova-build-model" }
rowan = "0.15.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["time"] }
tracing = { workspace = true }
walkdir = "2"
lsp-types = "0.97"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt", "time"] }
nova-test-utils = { path = "../nova-test-utils", default-features = false }
