[package]
name = "nova-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
nova-cache = { path = "../nova-cache" }
nova-fuzzy = { path = "../nova-fuzzy" }
nova-framework-spring = { path = "../nova-framework-spring" }
nova-index = { path = "../nova-index" }
nova-project = { path = "../nova-project" }
nova-syntax = { path = "../nova-syntax" }
crossbeam-channel = "0.5"
notify = "6.1"
nova-scheduler = { path = "../nova-scheduler" }
nova-vfs = { path = "../nova-vfs" }
rowan = "0.15.17"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
