[package]
name = "nova-syntax"
version.workspace = true
edition = "2021"

[features]
# Enables internal instrumentation used by downstream integration tests.
test-parse-counter = []

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
thiserror.workspace = true
nova-core = { path = "../nova-core" }
nova-types = { path = "../nova-types" }
nova-memory = { path = "../nova-memory" }
nova-vfs = { path = "../nova-vfs" }
rkyv = { version = "0.7", features = ["validation"] }
rowan = "0.15.17"
text-size = "1.1.1"
unicode-ident = "1"
tracing = { workspace = true }

[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4.0"
xtask = { path = "../xtask" }
nova-test-utils = { path = "../nova-test-utils", default-features = false, features = ["javac"] }

[[bench]]
name = "parse_java"
harness = false
