[package]
name = "nova-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
nova-core = { path = "../nova-core" }
rowan = "0.15.17"
text-size = "1.1.1"
unicode-ident = "1"

[dev-dependencies]
pretty_assertions = "1.4.0"
