[package]
name = "nova-syntax"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
nova-core = { path = "../nova-core" }
nova-types = { path = "../nova-types" }
nova-memory = { path = "../nova-memory" }
nova-vfs = { path = "../nova-vfs" }
rowan = "0.15.17"
text-size = "1.1.1"
thiserror = { workspace = true }
unicode-ident = "1"

[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4.0"
xtask = { path = "../xtask" }
nova-test-utils = { path = "../nova-test-utils", default-features = false }

[[bench]]
name = "parse_java"
harness = false
