[package]
name = "nova-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
nova-core = { path = "../nova-core" }
nova-types = { path = "../nova-types" }
nova-memory = { path = "../nova-memory" }
nova-vfs = { path = "../nova-vfs" }
rowan = "0.15.17"
text-size = "1.1.1"
unicode-ident = "1"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
